#!/usr/bin/env python

import sys
import os
import subprocess


def getCommandLine(rm):
    rm += ' '
    return ('sudo ' if isRoot() else '') + rm + ' '.join(sys.argv[1:])


def reconfirm():

    print('\033[1;91m[DANGER]\033[1;93m You are going to execute disastrous command! \033[1;91m[DANGER]')
    print('\033[4;93m$ ' + getCommandLine('rm') + '\033[m')
    print('\033[1;93mAre you sure to continue? [N/y]\033[m')

    if sys.stdin.readline().strip().lower() != 'y':
        print('\033[1;93mOperation aborted.\033[m')
        sys.exit(1)

    return True


def isRoot():
    return subprocess.Popen(['whoami'], stdout=subprocess.PIPE).communicate()[0].strip() == 'root'


def getHome():
    for line in subprocess.Popen(['env'], stdout=subprocess.PIPE).communicate()[0].split('\n'):
        if line.startswith('HOME'):
            return line.split('/')[-1]

    return 'home'


def determineCommandLine():

    if isRoot():
        if reconfirm():
            return

    home = getHome()

    for givenOption in sys.argv[1:]:
        if '/' == givenOption or '.' == givenOption:
            if reconfirm():
                return

        for dangerousOption in ('usr', 'bin', 'etc', 'var', 'home', 'dev', 'sbin', 'boot', 'lib', 'opt', 'proc', 'root', 'sys', 'run', 'mnt', \
                                'Documents', 'Downloads', 'Desktop', 'Pictures', 'Music', 'Public', 'Videos', home, \
                                '-rf', '-fr', '-f', '-r'):
            if dangerousOption in givenOption:
                if reconfirm():
                    return


if __name__ == '__main__':

    determineCommandLine()
    os.system(getCommandLine('rm.org -v'))
